# Generated by Django 6.0.3 on 2026-03-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('IOT', 'Internet of Things'), ('BE', 'Backend & Scalability'), ('CV', 'Computer Vision'), ('AT', 'Automation & Data')], max_length=3)),
                ('technologies', models.JSONField(default=list)),
                ('problem_statement', models.TextField()),
                ('solution_architecture', models.TextField()),
                ('impact_metrics', models.CharField(max_length=255)),
                ('github_link', models.URLField(blank=True)),
                ('live_demo', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
