# Generated by Django 6.0.3 on 2026-03-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='live_demo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
