# Generated by Django 6.0.3 on 2026-03-28 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_project_options_project_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at'], 'verbose_name': 'Projeto de Engenharia', 'verbose_name_plural': 'Projetos de Engenharia'},
        ),
    ]
