# Generated by Django 6.0.3 on 2026-09-12 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_alter_project_options_remove_project_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Cursando', 'Cursando'), ('Concluído', 'Concluído'), ('Trancado', 'Trancado')], default='Concluído', max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Jornada Acadêmica',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=200)),
                ('date_info', models.CharField(blank=True, max_length=100, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('link', models.URLField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Certificação',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('lattes', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Informação de Contato',
                'verbose_name_plural': 'Informações de Contato',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('period', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Experiência Profissional',
                'ordering': ['order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(blank=True, max_length=50, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Habilidade',
                'ordering': ['order', '-id'],
            },
        ),
    ]
