# Generated by Django 6.0.3 on 2026-09-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_academicjourney_certification_contactinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Em construção', 'Em construção'), ('Concluído', 'Concluído')], default='Em construção', max_length=50),
        ),
    ]
