# Generated by Django 6.0.3 on 2026-03-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('cpu_usage', models.FloatField()),
                ('memory_usage', models.FloatField()),
                ('is_online', models.BooleanField(default=True)),
                ('last_ping', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
